config/routes.rb
Rails.application.routes.draw do
  mount ForAdmin::Engine => '/', constraints: { subdomain: 'admin' }

  constraints subdomain: '' do
    root 'welcome#index'

    get 'login' => 'refugee_sessions#new'
    post 'login' => 'refugee_sessions#create'
    delete 'logout' => 'refugee_sessions#destroy'

    get 'authenticate' => 'refugee_sessions#authenticate'
    patch 'authenticate' => 'refugee_sessions#do_authenticate'

    get 'profile' => 'profile#show'
    get 'profile/new' => 'profile#new'
    post 'profile/new' => 'profile#create'

    resources :notices, only: [:index, :show]

    namespace :profile do
      get 'basic-info' => 'basic_info#edit'
      patch 'basic-info' => 'basic_info#update'

      get 'password' => 'password#edit'
      patch 'password' => 'password#update'

      get 'vulnerabilities' => 'vulnerabilities#edit'
      patch 'vulnerabilities' => 'vulnerabilities#update'

      get 'supplies' => 'supplies#edit'
      patch 'supplies' => 'supplies#update'

      get 'allergens' => 'allergens#edit'
      patch 'allergens' => 'allergens#update'

      get 'skills' => 'skills#edit'
      patch 'skills' => 'skills#update'
    end

    get 'family' => 'family#show'
    get 'family/edit' => 'family#edit'
    patch 'family/update' => 'family#update'
  end
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def index
    @notices = Notice.order(updated_at: :desc, created_at: :desc)
  end

  def show
    @notice = Notice.find(params[:id])
  end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/index.html.erb
<% provide(:title, 'お知らせ') %>
<ol class="breadcrumb">
  <li><%= link_to 'ホーム', root_path %></li>
  <li class="active">お知らせ</li>
</ol>
<%= render 'shared/flash' %>
<h1>お知らせ</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>日時</th>
      <th>内容</th>
    </tr>
  </thead>
  <tbody>
    <% @notices.each do |n| %>
      <tr>
        <td><%= format_time(n.updated_at) %></td>
        <td><%= link_to n.title, notice_path(n) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notices/show.html.erb
<% provide(:title, @notice.title) %>
<ol class="breadcrumb">
  <li><%= link_to 'ホーム', root_path %></li>
  <li><%= link_to 'お知らせ', notices_path %></li>
  <li class="active"><%= @notice.title %></li>
</ol>
<%= render 'shared/flash' %>
<h1><%= @notice.title %></h1>
<ul class="list-unstyled notice-datetime">
  <% if @notice.updated_at != @notice.created_at %>
    <li>
      <span class="label label-default">掲載</span>
      <%= format_time(@notice.created_at) %>
    </li>
    <li>
      <span class="label label-primary">更新</span>
      <%= format_time(@notice.updated_at) %>
    </li>
  <% else %>
    <li>
      <span class="label label-primary">掲載</span>
      <%= format_time(@notice.created_at) %>
    </li>
  <% end %>
</ul>
<%= simple_format(@notice.content) %>